# -*- coding: utf-8 -*-
"""Prodigy Task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19OWKj4Ox20QNcUhqO15pXx-2wxTLt2iY
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load the CSV file
df = pd.read_csv("/content/population_data.csv")

# Get the latest year in the dataset
latest_year = df.columns[-1]

# Sort countries by population in the latest year
top_countries = df[['Country Name', latest_year]].sort_values(by=latest_year, ascending=False).head(10)

# Plotting
plt.figure(figsize=(12, 6))
bars = plt.bar(top_countries['Country Name'], top_countries[latest_year], color='skyblue')
plt.xlabel("Country")
plt.ylabel("Population")
plt.title(f"Top 10 Most Populous Countries ({latest_year})")
plt.xticks(rotation=45)
plt.tight_layout()

# Annotate bars
for bar, pop in zip(bars, top_countries[latest_year]):
    plt.text(bar.get_x() + bar.get_width() / 2, pop, f'{pop/1e6:.1f}M',
             ha='center', va='bottom', fontsize=9)

plt.show()